#
# SternalBoard - Scoreboard plugin for Spigot and paper servers
#
# Version: 2.2.4
# Author: xism4 and Jonakls
#
# Support discord: https://discord.com/invite/jmWk4pR2SG
# Spigot: https://www.spigotmc.org/resources/sternalboard-lightweight-animated-scoreboard.89245/
# Polymart: https://polymart.org/resource/sternalboard-lightweight.1379
# MC-Market: https://www.mc-market.org/resources/20395/
# GitHub: https://github.com/ShieldCommunity/SternalBoard
#
# If you have any problem, contact us in discord or report issue in GitHub section
# Issues: https://github.com/ShieldCommunity/SternalBoard/issues

settings:
  animated: false
  # Select scoreboard mode: NORMAL, WORLD, PERMISSION
  #
  # NORMAL - scoreboard for all players
  # WORLD - scoreboard per world, u can configure in scoreboard-world section
  # PERMISSION - scoreboard per permission, u can configure in scoreboard-permission section
  mode: NORMAL
  scoreboard-interval-update: 20
  scoreboard:
    title: '&b&lMine&f&lPlot&a&l.PL'
    lines:
      - '&8&m+-------------------+'
      - ''
      - '&a&l‚ñº &bInformacje:'
      - '&f‚óè &f‚ò∫ &7Tw√≥j Nick: &a&l%player_name%'
      - '&f‚óè &3üéµ &7Ranga: &b%vault_prefix%'
      - '&f‚óè &aüíµ &7Saldo: &6&l$&b&l%vault_eco_balance_formatted%'
      - '&f‚óè &6üëë &7Pa≈Ñstwo: &e&l%kingdoms_kingdom_name%'
      - '&f‚óè &4‚åõ &7Czas Gry: &2%playtime_time%'
      - '&f‚óè &düë• &7Gracze online: &c&l%server_online%'

  #Option to disable some scoreboards from worlds
  world-blacklist:
    enabled: true
    worlds:
      - "your-world"
      - "your-world2"

#
# Scoreboard per world configuration
#
# If world no exist or is not configured, will use scoreboard section
scoreboard-world:
  'world':
    title: '&b&lSternal&f&lBoard &d&lWORLD'
    lines:
      - '&8&m+-------------------+'
      - '      &6&lWORLD'
      - '&a&l‚ñº &bData:'
      - '&f‚óè &7Nick: &b%player_name%'
      - '&f‚óè &7Rank: &b%vault_rank%'
      - '&f‚óè &7Coins: &e%vault_eco_balance_formatted%'
      - ''
      - '&a&l‚ñº &bExample:'
      - '&f‚óè &7Lobby: &b#1'
      - '&f‚óè &7Ping: &b%player_ping%'
      - '&f‚óè &7Players: &b%bungee_total%'
      - ''
      - '&f‚óè &fIP: &bplay.yournetwork.com'
#
# Scoreboard per permission configuration
#
# If permission no exist or is not configured, will use scoreboard section
#
# Remember if u use this mode, u need to add permissions to your permission plugin
# Example: sternalboard.admin, sternalboard.mod, sternalboard.dev, sternalboard.owner
# If u have op, u will see all scoreboards, remember deny nodes in your permission plugin
scoreboard-permission:
  'admin':
    node: 'sternalboard.admin'
    title: '&b&lSternal&f&lBoard &d&lADMIN'
    lines:
      - '&8&m+-------------------+'
      - '      &6&lADMIN'
      - '&a&l‚ñº &bData:'
      - '&f‚óè &7Nick: &b%player_name%'
      - '&f‚óè &7Rank: &b%vault_rank%'
      - '&f‚óè &7Coins: &e%vault_eco_balance_formatted%'
      - ''
      - '&a&l‚ñº &bExample:'
      - '&f‚óè &7Lobby: &b#1'
      - '&f‚óè &7Ping: &b%player_ping%'
      - '&f‚óè &7Players: &b%bungee_total%'
      - ''
      - '&f‚óè &fIP: &bplay.yournetwork.com'
  'mod':
    node: 'sternalboard.mod'
    title: '&b&lSternal&f&lBoard &d&lMOD'
    lines:
      - '&8&m+-------------------+'
      - '      &6&lMOD'
      - '&a&l‚ñº &bData:'
      - '&f‚óè &7Nick: &b%player_name%'
      - '&f‚óè &7Rank: &b%vault_rank%'
      - '&f‚óè &7Coins: &e%vault_eco_balance_formatted%'
      - ''
      - '&a&l‚ñº &bExample:'
      - '&f‚óè &7Lobby: &b#1'
      - '&f‚óè &7Ping: &b%player_ping%'
      - '&f‚óè &7Players: &b%bungee_total%'
      - ''
      - '&f‚óè &fIP: &bplay.yournetwork.com'
  'dev':
    node: 'sternalboard.dev'
    title: '&b&lSternal&f&lBoard &d&lDEV'
    lines:
      - '&8&m+-------------------+'
      - '      &6&lDEV'
      - '&a&l‚ñº &bData:'
      - '&f‚óè &7Nick: &b%player_name%'
      - '&f‚óè &7Rank: &b%vault_rank%'
      - '&f‚óè &7Coins: &e%vault_eco_balance_formatted%'
      - ''
      - '&a&l‚ñº &bExample:'
      - '&f‚óè &7Lobby: &b#1'
      - '&f‚óè &7Ping: &b%player_ping%'
      - '&f‚óè &7Players: &b%bungee_total%'
      - ''
      - '&f‚óè &fIP: &bplay.yournetwork.com'
  'owner':
    node: 'sternalboard.owner'
    title: '&b&lSternal&f&lBoard &d&lOWNER'
    lines:
        - '&8&m+-------------------+'
        - '      &6&lOWNER'
        - '&a&l‚ñº &bData:'
        - '&f‚óè &7Nick: &b%player_name%'
        - '&f‚óè &7Rank: &b%vault_rank%'
        - '&f‚óè &7Coins: &e%vault_eco_balance_formatted%'
        - ''
        - '&a&l‚ñº &bExample:'
        - '&f‚óè &7Lobby: &b#1'
        - '&f‚óè &7Ping: &b%player_ping%'
        - '&f‚óè &7Players: &b%bungee_total%'
        - ''
        - '&f‚óè &fIP: &bplay.yournetwork.com'
